/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
  	extend: {
  		colors: {
  			page: 'hsl(var(--page-bg))',
  			background: 'hsl(var(--background))',
  			foreground: 'hsl(var(--foreground))',
  			surface: 'hsl(var(--surface))',
  			surfaceMuted: 'hsl(var(--surface-muted))',
  			surfaceForeground: 'hsl(var(--surface-foreground))',
  			mutedForeground: 'hsl(var(--muted-foreground))',
  			card: 'hsl(var(--card))',
  			cardForeground: 'hsl(var(--card-foreground))',
  			popover: 'hsl(var(--popover))',
  			popoverForeground: 'hsl(var(--popover-foreground))',
  			accent: 'hsl(var(--accent))',
  			accentForeground: 'hsl(var(--accent-foreground))',
  			border: 'hsl(var(--border))',
  			input: 'hsl(var(--input))',
  			primary: 'hsl(var(--primary))',
  			primaryForeground: 'hsl(var(--primary-foreground))',
  			destructive: 'hsl(var(--destructive))',
  			destructiveForeground: 'hsl(var(--destructive-foreground))',
  			ring: 'hsl(var(--ring))',
  			planned: 'hsl(var(--event-planned-bg))',
  			active: 'hsl(var(--event-active-bg))',
  			win: 'hsl(var(--event-win-bg))',
  			lose: 'hsl(var(--event-lose-bg))',
  			plannedText: 'hsl(var(--event-planned-text))',
  			activeText: 'hsl(var(--event-active-text))',
  			winText: 'hsl(var(--event-win-text))',
  			loseText: 'hsl(var(--event-lose-text))',
  			plannedBorder: 'hsl(var(--event-planned-border))',
  			activeBorder: 'hsl(var(--event-active-border))',
  			winBorder: 'hsl(var(--event-win-border))',
  			loseBorder: 'hsl(var(--event-lose-border))',
  			danger: 'hsl(var(--danger))',
  			dangerForeground: 'hsl(var(--danger-foreground))',
  			overlay: 'hsl(var(--overlay))',
  			muted: 'hsl(var(--muted))',
  			skeleton: 'hsl(var(--skeleton))',
  			sidebar: {
  				DEFAULT: 'hsl(var(--sidebar-background))',
  				foreground: 'hsl(var(--sidebar-foreground))',
  				primary: 'hsl(var(--sidebar-primary))',
  				'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
  				accent: 'hsl(var(--sidebar-accent))',
  				'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
  				border: 'hsl(var(--sidebar-border))',
  				ring: 'hsl(var(--sidebar-ring))'
  			},
			surface_second: "hsl(var(--surface-bg))",
  		}
  	}
  },
  plugins: [require("tailwindcss-animate")],
};
