export const GOAL_LONG_PRESS_DURATION_MS = 600;
export const GOAL_CALENDAR_LONG_PRESS_DURATION_MS = 1000;
export const GOAL_CALENDAR_HOLD_RESET_DURATION_MS = 320;
export const GOAL_CALENDAR_HOLD_FADE_OUT_DURATION_MS = 180;
